### ISSUE TITLE
Having issues when used with KerasClassifier

### ISSUE THREAD

**Issue by hanzigs** [timzatko/Sklearn-Nature-Inspired-Algorithms#1] opened 2020-07-28 04:24 UTC
Hi,
Thanks for this library, working very well,
I tried with KerasClassifier from
```
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
```
my Spyder ide getting hanged in half way of epoch tuning
Is this not supposed to work with keras, still a scikit learn wrapper?
Thanks

**Comment by timzatko** [comment] 2020-07-31 08:27
Hi! Can you provide me a minimal code example where you encounter this issue so I can reproduce it? Thanks.

**Comment by hanzigs** [comment] 2020-07-31 10:12
Thanks for that, here is the code
```
    def create_model():
     	model = Sequential()
    	model.add(Dense(25, input_dim=25, activation='relu'))
    	model.add(Dense(1, activation='sigmoid'))
    	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    	return model
    model = KerasClassifier(build_fn=create_model)
    param_grid = dict(batch_size=batch_size, epochs=epochs)
    #grid = GridSearchCV(estimator=model, param_grid=param_grid, , cv=3)
    grid = NatureInspiredSearchCV(model, cv = 3, param_grid=param_grid, verbose=1,  algorithm='ba',  population_size=25,  max_n_gen=100,  max_stagnating_gen=10, runs=5, scoring='accuracy', random_state=42)
    #earlyStop = EarlyStopping(monitor='loss', mode='min', verbose=VERBOSE, patience=10) #min_delta=0.01)
    grid_result = grid.fit(X_train, y_train)#, callbacks=[earlyStop]) 
```

**Comment by timzatko** [comment] 2020-07-31 14:15
I was not able to reproduce your issue, and it works for me, here is my code snippet.

https://colab.research.google.com/drive/1a8amOewiJbbaOAChkI3a9dXPS81s_xwD?usp=sharing

**Comment by hanzigs** [comment] 2020-07-31 20:18
sorry for inconvenience, will try again,

**Comment by hanzigs** [comment] 2020-07-31 21:43
Thanks for that,it Worked well, not sure what happened before, tested with Keras, Scikit-learn and XGB.

**Comment by timzatko** [comment] 2020-08-04 11:44
Great! Glad it works, closing the issue then.

**Closed by timzatko** 2020-08-04 11:44 UTC
Labels: bug
